### ISSUE TITLE
添加 README

### ISSUE THREAD

**Issue by liupcs** [liupcs/tata#2]
便于大家了解项目

**Comment by liupcs** [comment]
@weipcs 你有什么好的主意呢

**Comment by weipcs** [comment]
>1. 最开头输入【>】后面跟要回复哪段记录
>2. 直接选中要回复的记录，然后按【R】键
》>点一下时间赋值地址栏中的链接，复制到下面
https://github.com/liupcs/tata/issues/2#issuecomment-497909852

编号为#2的表示为2的事物卡片
